### ISSUE TITLE
App Crashes when adapter have no item or empty list and then by pressing delete button

### ISSUE THREAD

**Issue by hassaanjamil** [yzhong52/Example-FragmentStatePagerAdapter#1]

**Comment by yzhong52** [comment]
@hassaanjamil thanks, I'll look into the issue.

**Comment by yzhong52** [comment]
Fixed: https://github.com/yzhong52/Example-FragmentStatePagerAdapter/commit/6e83678924f4cf84772fbb3ed9c150711a2a3fa8#diff-358d62ce690164b2d13aebdd1dd8bf18R37
